#!/usr/bin/env ruby

require "json"

json = ENV.fetch("VCAP_SERVICES")
vcap_services = JSON.parse(json)
user_provided = vcap_services.fetch("user-provided")

targets_access_name = user_provided[0]['credentials']['access_name']

prometheus_access = user_provided.detect { |e| e["name"] == targets_access_name }

raise "The #{targets_access_name} user-provided service has not been set up." unless prometheus_access

prometheus_access.fetch("credentials").each { |k, v| print "#{k}=#{v} " }
